export const PATHS = [
  {
    name: 'Path of Blood', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>The foundation art of Clan Tremere and the path nearly every apprentice learns first, built on turning Kindred vitae itself into an instrument. A student who wants a different primary path should be ready to explain the choice to her Regent, though it does happen.</p>`, powers: {
      lvl1: { name: 'A Taste for Blood', desc: `<p>By touching a sample of blood, the vampire determines how much vitae remains in the subject, how recently they fed, approximate Generation (if Kindred), and whether they have committed diablerie.</p><p><b>System:</b> Roll Perception + Occult (diff 7). Successes determine the amount and accuracy of information gained. Three or more successes reveal diablerie.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Blood Rage', desc: `<p>Through touch, the vampire forces another Kindred to expend blood points against their will.</p><p><b>System:</b> Roll Dexterity + Subterfuge (diff 6). Each success forces the target to spend 1 blood point immediately (can exceed per-turn Generation limits). The caster chooses how the blood is spent (boosting attributes, healing, etc.). Each success also increases the target's frenzy difficulty by 1. Cannot be used on yourself to bypass Generation limits.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Blood of Potency', desc: `<p>The vampire temporarily concentrates their blood, effectively lowering their Generation.</p><p><b>System:</b> Roll Intelligence + Occult (diff 8). Each success provides one step down in Generation or one hour of duration; successes must be split between both. Cannot be used while already active. If diablerized during the effect, the diablerist only gains benefit of the actual Generation. Childer are created at the sire's true Generation. Blood exceeding the normal pool maximum dilutes when the power ends.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Theft of Vitae', desc: `<p>The vampire siphons blood directly from a visible target up to 50 feet away, pulling it through the air in a physical stream.</p><p><b>System:</b> Roll Intelligence + Medicine (diff 6). Each success transfers 1 blood point. Counts as ingesting the blood (for blood bond purposes, etc.) but prevents being bound. Obviously supernatural; public use is a Masquerade breach.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Cauldron of Blood', desc: `<p>The vampire boils blood inside a target's veins through physical contact.</p><p><b>System:</b> Roll Willpower (diff 6). Each success boils 1 blood point, dealing 1 level of aggravated damage per point boiled (soakable only with Fortitude). A single success kills any mortal.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'Elemental Mastery', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Communion with, and command over, the inanimate. This path speaks only to unliving matter; nothing that grows will answer it, and thaumaturges who want power over living things study The Green Path instead.</p>`, powers: {
      lvl1: { name: 'Elemental Strength', desc: `<p>The caster borrows the patience and power of stone and steel, hardening his dead frame without burning through extra vitae.</p><p><b>System:</b> Distribute 3 temporary dots between Strength and Stamina. They last one turn per success, and a point of Willpower buys one more turn. The effect cannot be stacked; one use must expire before the next begins.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Wooden Tongues', desc: `<p>Every object carries a dim spirit that half-remembers what has passed before it. This power lets the vampire ask, though a chair's idea of a memorable evening rarely matches a Kindred's.</p><p><b>System:</b> Successes govern how much the object recalls and how useful it is: one might yield a boulder's vague memory of an old fire, three a figure hurrying past in the dark, five a description sharp enough to name the passerby.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Animate the Unmoving', desc: `<p>Objects wake and move at the caster's direction, flexing in ways their makers never intended: a barstool can scuttle on its legs, a holstered pistol can fire, a statue can walk like a man. Nothing may act wholly beyond its form, so the door stays on its hinges.</p><p><b>System:</b> Fewer than four successes means spending a point of Willpower. Each use animates one object up to human size, and the caster can run as many at once as his Intelligence rating. Control lasts while the object remains in his sight, up to an hour, and he is free to act in the meantime.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Elemental Form', desc: `<p>The vampire remakes herself as an inanimate object of roughly her own mass: a statue, a desk, a motorcycle. Nothing as large as a house, nothing as small as a pen.</p><p><b>System:</b> Successes measure how convincing the counterfeit is; at least three are needed to keep using senses or Disciplines while transformed. The shape holds for the rest of the night, though she may drop it at will.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Summon Elemental', desc: `<p>The caster calls up one of the old elemental spirits: salamander of fire, sylph of air, gnome of earth, undine of water. Stranger patrons of glass, lightning, and worse get whispered about, and Vienna asks pointed questions of those doing the whispering. He must stand near a quantity of the matching element, and what answers obeys only as far as it is made to.</p><p><b>System:</b> Casting successes set the spirit's strength: it starts at 3 in every Physical and Mental Attribute and gains one Physical dot per success. Mastering it then takes Manipulation + Occult against difficulty 4 + those successes. A botch turns the spirit on its summoner and a failure sets it loose; one success buys peace, two a favor for a price, three one reasonable service, four any single task short of self-destruction, and five faithful service even over several nights of risk. The Storyteller sets its Abilities, attacks, and elemental tricks.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Green Path', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Dominion over everything that grows, from moss to redwood, living or dead. Rivals sneer at gardener's magic right up until the garden closes over them; the path is as quiet, and as strong, as the green world it commands.</p>`, powers: {
      lvl1: { name: 'Herbal Wisdom', desc: `<p>A touch opens conversation with a plant's spirit. The oldest trees hold wisdom to shame the oracles; crabgrass mostly remembers shoes.</p><p><b>System:</b> Successes set the depth of the answer: cryptic flashes at one, a pair of clear images at two, a plain answer to a simple question at three, a thorough reply at four, and at five everything the spirit knows about the subject. Untangling a cryptic response may take Intelligence + Occult.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Speed the Season\'s Passing', desc: `<p>The caster runs a plant's clock forward at a touch, forcing years of growth in minutes or collapsing it into rot just as quickly.</p><p><b>System:</b> One success is a growth spurt or a hard season; three visibly swell or wither the target; five raise a full plant from seed, or crumble one to dust, inside a few minutes. Against wooden weapons, two successes weaken one, three ruin it, and five let it disintegrate in the wielder's hand.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Dance of Vines', desc: `<p>Vegetation up to the caster's own mass wakes and serves. Leaves cross a desktop in step, ivy takes dictation, and jungle creepers learn to strangle; wise burglars distrust a Tremere's potted rowan.</p><p><b>System:</b> The animated growth obeys perfectly for one turn per success. In combat it fights with Strength and Dexterity equal to half the caster's Willpower (rounded down) and Brawl one below his own. It cannot uproot itself and go walking, but a hundred kilograms of kudzu covers remarkable ground exactly where it lies.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Verdant Haven', desc: `<p>Branch, leaf, and vine weave themselves into a sealed dome around the caster, an obviously unnatural shelter of green with no visible entrance, warded against the uninvited and, done well, proof even against the sun. Stories credit it with healing virtues no Kindred has managed to confirm.</p><p><b>System:</b> Requires standing in heavy vegetation; the dome closes over three turns. Entering uninvited demands beating the caster's casting successes on a single Wits + Survival roll at a difficulty of the caster's Willpower. The haven lasts until the next sunset, or until the caster ends or abandons it, and with four or more successes sunlight cannot enter unless the dome is physically breached.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Awaken the Forest Giants', desc: `<p>The masterwork of the path: a whole tree hauls its roots from the earth and walks at the caster's word, slow, vast, and horribly strong.</p><p><b>System:</b> Touch the tree and roll; every success must then be paid for with a blood point and grants one turn of motion. The tree obeys spoken commands with Strength and Stamina equal to the caster's Thaumaturgy rating, Dexterity 2, and the caster's own Brawl. Bashing damage cannot harm it and lethal dice pools against it are halved. When the animation ends it roots itself wherever it stands, driving through asphalt if need be, and cannot walk again until the next night.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'Hands of Destruction', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>The war-magic of the Sabbat's blood sorcerers, only rarely seen in Camarilla chantries. Its history is ugly and its reputation worse; more than a few Tremere refuse to touch it, repeating the old whisper that something infernal taught it first.</p>`, powers: {
      lvl1: { name: 'Decay', desc: `<p>Entropy on command: whatever the caster holds withers, rusts, and rots, years passing in moments. Only the unliving is vulnerable, though dead organic matter qualifies.</p><p><b>System:</b> On a success, the touched object ages ten years for every minute of contact. Breaking contact ends the effect, and starting over costs a fresh blood point and roll. Vampires are untouched by it.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Gnarl Wood', desc: `<p>Wood twists at a glance into shapes no carpenter intended: stocks warp, hafts curl, and a hunter's stakes knot themselves into driftwood. The material survives; its usefulness does not.</p><p><b>System:</b> Sight alone suffices, no touch needed. Every blood point spent, up to the caster's per-turn generational limit, gnarls some twenty-five kilograms of visible wood, spread across as many objects as are in view.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Acidic Touch', desc: `<p>The caster's vitae turns to a caustic bile weeping from her skin, chewing through metal, wood, and flesh alike. Her own body ignores it entirely.</p><p><b>System:</b> One blood point transmutes into enough acid to eat through half a centimeter of steel plate or a hand's depth of wood. Unarmed attacks slicked with it inflict aggravated damage and cost one blood point per turn to sustain.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Atrophy', desc: `<p>A limb shrivels in seconds into dried skin over bone. For mortals there is no road back.</p><p><b>System:</b> The victim resists with Stamina + Athletics against difficulty 8: three successes shrug the power off, two leave the limb at +1 difficulty to use, one at +2, and none cripple it outright. Mortal damage is forever; a vampire can spend five blood points to restore the limb. Only arms, legs, and extremities can be targeted, never head or torso.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Turn to Dust', desc: `<p>The path's last lesson pours decades into a body at a touch, leaving mortals white-haired, withered, or dead in moments.</p><p><b>System:</b> Each success ages the victim ten years. Resisting takes Stamina + Courage against difficulty 8 and demands beating the caster's total outright; it is all or nothing. The years mean nothing to the deathless: at worst a Kindred target pales and dries out, losing 1 Appearance until the next night.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Lure of Flames', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Conjured fire from no natural source; more than one vampire mutters that the path borrows it straight from Hell. Flame held by the caster is inert, a cold light cupped in the palm that burns nothing and frightens no one. Released, it becomes entirely real, entirely ordinary fire, outside anyone's control, and everything the Damned dread about burning applies.</p><p><b>System:</b> Declare the flame's intended spot before rolling. One success lights it in the caster's own hand and five put it anywhere in sight; on a shortfall it lands where the Storyteller likes, with accuracy of roughly ten meters per success. Only Fortitude dice may soak this fire. The caster's own conjured flame neither burns him nor tests his nerve, but any blaze it kindles treats him like everyone else, and other Kindred who see it may well frenzy.</p>`, powers: {
      lvl1: { name: 'Candle', desc: `<p>Soak difficulty 3; one level of aggravated damage per turn.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Palm of Flame', desc: `<p>Soak difficulty 4; one level of aggravated damage per turn.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Campfire', desc: `<p>Soak difficulty 5; two levels of aggravated damage per turn.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Bonfire', desc: `<p>Soak difficulty 7; two levels of aggravated damage per turn.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Inferno', desc: `<p>Soak difficulty 9; three levels of aggravated damage per turn.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'Neptune\'s Might', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>A quiet path with a small, devoted following stretching back centuries, built on mastery of standing water and, at its heights, of the water inside bodies. From the third dot onward its student may specialize in fresh or salt water, lowering difficulties by one in the chosen medium and raising them by one in the other; blood counts as neither.</p>`, powers: {
      lvl1: { name: 'Eyes of the Sea', desc: `<p>Still water becomes a window into everything that has happened on, in, or around it, as though the pool itself consented to testify. Older practitioners credit water spirits; their students roll their eyes.</p><p><b>System:</b> Successes reach back one day, one week, one month, one year, or ten years. Making out fine detail may call for Perception + Occult. Only standing water serves: a lake or a puddle, never a river, a sewer, or a wine glass.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Prison of Water', desc: `<p>Water rears up and closes around a victim like living shackles. A bathtub's worth is the working minimum; more is better.</p><p><b>System:</b> Breaking loose requires more successes on a Strength roll, difficulty 8 (Potence adds to it), than the caster scored. One prison per victim, though the caster may bind several targets separately and dissolve any of them at will. With less than a tubful available, the activation difficulty rises by one.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Blood to Water', desc: `<p>The mistress of this power turns other liquids into water at a touch, and the liquid she likes best runs in veins. Mortals die of it in minutes; Kindred feel their hoarded vitae thin into nothing.</p><p><b>System:</b> Each success converts one of the victim's blood points to water, and a single success finishes a mortal. A vampire also suffers dice penalties as though wounded one health level per point lost. The water evaporates from the system at a point per hour, but the blood is simply gone. Other fluids can be transmuted at one lower difficulty unless dangerous or magical, always by touching the substance or its vessel.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Flowing Wall', desc: `<p>The caster raises standing water into a rampart, sheer and unclimbable, that even the restless dead struggle to cross. The old folklore about vampires and running water probably began with garbled accounts of this.</p><p><b>System:</b> Touch the water's surface, spend three Willpower points plus the usual blood, and roll: each success buys three meters of height or width, laid out in a straight line anywhere in sight. The wall stands until sunrise. It can be flown over but never climbed, and passing through it costs any supernatural being, ghosts included, three successes on a single Willpower roll at difficulty 9.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Dehydrate', desc: `<p>At the path's summit the caster pulls water straight out of a target: soaked clothes dry, puddles vanish before rival thaumaturges can use them, and bodies collapse into mummified husks.</p><p><b>System:</b> Works on anything in sight. The victim's Stamina + Fortitude roll at difficulty 9 stands in for soak; every net success inflicts an unsoakable level of lethal damage, healed normally. Vampires lose blood points instead until none remain, then take damage like mortals. The victim must also roll Courage, difficulty 3 + the caster's successes, or spend the following turn doubled over in agony.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'Movement of the Mind', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Telekinesis by way of vitae. Whatever the caster seizes at a distance can be lifted, spun, worked, or hurled exactly as if held in hand, and more than one Tremere haven is guarded by unattended sabers and pistols standing sentry. Mortal onlookers tend to handle it poorly.</p><p><b>System:</b> Successes set the duration at one turn apiece; fresh rolls, without new blood, keep the grip, and five or more successes on the first roll hold for the full scene. Releasing something and seizing it again is a new use and a new blood point. A living target fights back with opposed Willpower rolls each turn. The path has no separate powers, only rising tonnage; from three dots the caster can levitate herself at about a run no matter her weight, and from four she can throw what she holds with an effective Strength equal to her path rating.</p>`, powers: {
      lvl1: { name: '', desc: `<p>Up to half a kilogram (one pound).</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: '', desc: `<p>Up to 10 kilograms (20 pounds).</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: '', desc: `<p>Up to 100 kilograms (200 pounds).</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: '', desc: `<p>Up to 250 kilograms (500 pounds).</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: '', desc: `<p>Up to 500 kilograms (1000 pounds).</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Path of Conjuring', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Summoning made systematic: matter called out of empty air, bounded only by the caster's knowledge and nerve. Conjured things are eerily perfect and eerily generic, the identical knife every single time, unscratched and unmarked, and nothing larger than the conjurer herself will come. Familiarity governs the work; conjuring from imagination or a photograph raises the difficulty, while an object known intimately may lower it. Successes on the roll set the quality of the copy, from shoddy at one to nearly flawless at five.</p>`, powers: {
      lvl1: { name: 'Summon the Simple Form', desc: `<p>Single-piece, single-substance objects only: a length of pipe, a stake, a slab of granite. Nothing that moves, nothing mixed.</p><p><b>System:</b> The object persists only while fed Willpower, one point per turn; starve it and it fades from existence.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Permanency', desc: `<p>Makes an Ignis Fatuus or Fata Morgana illusion persist even when the vampire is not present.</p><p><b>System:</b> Spend 1 blood point. The illusion becomes permanent until deliberately dissolved, including programmed motion from Apparition.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Magic of the Smith', desc: `<p>The conjurer graduates to machinery: firearms, engines, phones, anything whose parts must move together.</p><p><b>System:</b> Such creations are permanent from the start and cost five blood points. Especially intricate devices may also demand an appropriate Knowledge roll, such as Crafts, Science, or Technology.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Reverse Conjuration', desc: `<p>What the path grants, this power revokes, unraveling any conjured object back into the nothing it came from, the caster's own work included.</p><p><b>System:</b> An extended roll: accumulate as many successes as the object's creator scored when calling it forth, and it ceases to exist.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Power Over Life', desc: `<p>The summit of the path calls up walking counterfeits of living beings: obedient, hollow-eyed, and without a will of their own. Dominate's Possession can put a rider inside one.</p><p><b>System:</b> Costs 10 blood points. The simulacrum is too intricate to hold together and dissolves into nothing within a week.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Path of Corruption', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>No one agrees where this path came from, and every theory on offer is worse than the last: demons taught it, the Clan carried it out of its mortal days, or the Followers of Set sold it for a price nobody will name. The Tremere deny that last one loudly, which keeps it in circulation. What the path does is not in question: it rots choices slowly from the inside, bending morals, appetites, and loyalties rather than barking commands like Dominate or stirring the moment like Presence. Its practitioners must know the heart's back alleys, and none may hold this path at a higher rating than their Subterfuge.</p>`, powers: {
      lvl1: { name: 'Contradict', desc: `<p>The caster snaps a decision in mid-arc and the victim does the darker opposite of what they intended: the pardon becomes an execution, the caress a cruelty. Not even the caster knows exactly what shape the reversal will take, only that it will be worse.</p><p><b>System:</b> Usable on anyone in sight, but never in combat or on purely reflexive acts. The target rolls Perception + Subterfuge against difficulty 2 + the caster's successes: two successes reveal an outside hand at work, three trace it to its source, four leave the victim frozen between the two choices, and five let the original action proceed. The Storyteller decides what the reversal looks like.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Subvert', desc: `<p>Where Contradict is a spark, Subvert is a slow leak. For the duration, the victim chases a temptation they have spent a lifetime keeping buried.</p><p><b>System:</b> Requires eye contact. The target resists with Perception + Subterfuge against a difficulty of their own Manipulation + Subterfuge; if the caster wins, the buried urge steers them for five minutes, an hour, a night, three nights, or a week by successes. The Storyteller chooses the desire, drawing on the victim's psychological Flaws or the shadow side of their Nature, and turning down a clear chance to indulge costs a point of Willpower.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Dissociate', desc: `<p>Divide and conquer, distilled. This power reaches into a bond between people and switches the warmth off: old friendships cool, love curdles into distance, and weak ties snap outright.</p><p><b>System:</b> Touch is required. The victim resists with Willpower against the caster's Manipulation + Empathy. On a loss they drop three dice from every Social roll, Discipline rolls included, for five minutes up to a week by successes, and any Vinculum ratings fall by three for the duration. Victims should be played withdrawn, suspicious, and cold; the Storyteller may charge Willpower for playing them any other way.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Addiction', desc: `<p>One exposure, one touch, and the craving takes root. Careful thaumaturges hook their victims on something only they can supply, which makes for steady income and better leverage.</p><p><b>System:</b> The victim must encounter the sensation, substance, or act in question as the caster touches them, then resists with Self-Control or Instinct against difficulty 3 + the caster's successes. Failure means true addiction lasting a number of weeks equal to the caster's Manipulation. The addict needs a nightly fix; each night denied strips a cumulative die from all pools (minimum one), and refusing an offered indulgence takes a Self-Control/Instinct roll at difficulty 8. Shaking it early is an extended nightly Self-Control/Instinct roll against the caster's Manipulation + Subterfuge, requiring triple the caster's successes, and a single lapse erases all progress.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Dependence', desc: `<p>The last power ties the victim's spirit to the caster's own. Away from her he is listless, hollow, and easy to lead; the Clan's pawns know the feeling well and usually blame the blood bond.</p><p><b>System:</b> Worked into ordinary conversation. The victim resists with Self-Control/Instinct against difficulty 3 + the caster's successes; failure bonds him for one night per success. A bonded victim can still hate her and still strike her, but loses one die from every pool while out of her presence, halves his dice to resist her Dominate, Presence, and mundane social pressure, and regains no Willpower except at her side.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Path of Mars', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>War-sorcery, kept alive by the few Sabbat who still practice blood magic and pointed squarely at the sect's battles, where it has turned more than one fight against elder opposition. Where most Thaumaturgy whispers, this path shouts. A handful of Camarilla Tremere are rumored to know it; fewer have the temperament to use it well.</p>`, powers: {
      lvl1: { name: 'War Cry', desc: `<p>The caster steels his will before battle, usually with a howled challenge, though warpaint or a self-inflicted cut serves some practitioners just as well. Fear and the powers of the dead find less purchase on him.</p><p><b>System:</b> For one scene the character's Courage rises by 1, and his Willpower counts as one higher against hostile powers (the Trait only, never the pool). The benefit can be gained once per scene.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Strike True', desc: `<p>The Blood guides a single blow home; the enemy may as well already be wearing the wound.</p><p><b>System:</b> One Brawl or Melee attack hits without a roll, counting as a one-success strike with no bonus damage dice. It can still be dodged, blocked, or parried, and the defender needs only a single success to do it. The power cannot be combined with multiple attacks from a split dice pool.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Wind Dance', desc: `<p>The caster moves like wind through grass, slipping out of blows almost before they are thrown.</p><p><b>System:</b> For a scene, she may dodge any number of attacks each turn at her full dice pool. This applies to dodging alone; attacking and dodging in the same turn still splits the pool as usual.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Fearless Heart', desc: `<p>Blood magic tunes the caster's dead body for war, all of it at once.</p><p><b>System:</b> Gain one dot each of Strength, Dexterity, and Stamina for a scene, respecting generational maximums (blood can still push past them as normal). Once per scene. Afterward the vampire must rest calmly for two hours or bleed away one blood point every 15 minutes until he does.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Comrades at Arms', desc: `<p>The master of the path shares its gifts with the pack, arming a whole War Party with a touch.</p><p><b>System:</b> Invoke any lower power of the path normally, then touch each ally to extend it to them: one roll for Comrades at Arms and the usual blood cost per recipient, with no limit on packmates beyond what the caster can pay.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Path of Technomancy', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>The youngest path in the Clan's official grimoires, worked out in the late 20th century and devoted to command over electronics, from phones to server racks. Its partisans call it proof that Thaumaturgy can keep pace with the world; conservative Regents call the marriage of Tremere magic and mortal science something close to blasphemy, and a few in Europe treat knowing it as grounds for expulsion. The Inner Council approved the path and has said nothing since, which suits nobody.</p>`, powers: {
      lvl1: { name: 'Analyze', desc: `<p>A touch pours understanding of a device into the caster's mind: what it is for, how it works, how to drive it. The insight is borrowed, not learned, and evaporates in minutes.</p><p><b>System:</b> Touch the device and roll: one success grants basic use, three real competence, five its full potential. The knowledge lasts a number of minutes equal to Intelligence. Software can be read at +2 difficulty, and only by touching the machine it is installed on; a drive or disc in hand tells nothing.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Burnout', desc: `<p>The caster overloads a device's power supply and lets physics do the rest. It cannot electrocute anyone directly, though a cooked pacemaker or engine controller raises its own problems.</p><p><b>System:</b> Range is 10 times Willpower in meters, at +1 difficulty without touch. One success stalls the device for a turn; two degrade it (+1 difficulty to use for the scene); three break it until repaired; four leave a permanent +1 difficulty even after repair; five write it off entirely. Very large systems run +2 to +4 difficulty, and hardened networks may resist with one to five dice (difficulty 6), each success cancelling one of the caster's. Against stored data, three successes wipe it and five put it beyond any mundane recovery.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Encrypt/Decrypt', desc: `<p>The caster mystically scrambles a machine's workings or a medium's contents so that only he can use them; a protected disc plays static for anyone else. Young Tremere have taken to calling it DRM.</p><p><b>System:</b> Touch the device or storage and roll: the successes become a difficulty penalty on anyone trying to use or read it without the caster's blessing. The effect lasts a number of weeks equal to permanent Willpower, or until the caster touches the item and spends a Willpower point to release it. It can also strip another caster's lock, rolled at +1 difficulty, cancelling success for success.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Remote Access', desc: `<p>The caster operates a machine without laying a finger on it, touching it with mind rather than telekinesis.</p><p><b>System:</b> Works on any device in sight. Successes cap both the duration in turns and the number of Ability dice usable through the connection (a caster with Technology 5 who rolls three successes drives the device with three dice). One device at a time. If the device is destroyed mid-connection, the snap-back inflicts five dice of bashing damage.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Telecommute', desc: `<p>The caster pours her consciousness into the network itself, riding connections across the world and working her arts on whatever machines she touches along the way.</p><p><b>System:</b> Touch any connected device and spend a Willpower point. Duration is five minutes per success, extendable by ten minutes per further Willpower point. Successes set the reach: roughly 40 kilometers at one, 400 at two, 1500 at three, 8000 at four, and anywhere on Earth at five. Other Technomancy powers work through the link at normal difficulty; anything else is at +2. A dropped connection hurls her home for eight dice of bashing damage.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Path of the Father\'s Vengeance', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>A path of judgment built on one thaumaturge's reading of the Book of Nod, every power an echo of some parable, delivered as a curse in Caine's name. The Sabbat argue bitterly over it, since wielding it comes close to claiming the Father's own authority; Tremere chantries know it too, if less scripturally. Every power requires the caster to pronounce the condemnation aloud where the target can hear it, or failing that, show it written. The curses bite only vampires: mortals, ghouls, and other creatures are beneath their notice.</p>`, powers: {
      lvl1: { name: 'Zillah\'s Litany', desc: `<p>Named for the wife who drank three times unknowing, this power drags every bond of blood into the light.</p><p><b>System:</b> The caster learns each blood bond and Vinculum the target carries, with names and rough psychic impressions of the vampires on the other end, strangers included.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'The Crone\'s Pride', desc: `<p>The caster lays the Crone's own hideousness on the target, the face that had to buy service with trickery because none was freely given.</p><p><b>System:</b> The target's Appearance drops to zero for one night. Social rolls simply fail for the duration, unless the target resorts to intimidation and browbeating.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'Feast of Ashes', desc: `<p>A curse for gluttons: the target's endless thirst is answered with a scavenger's diet.</p><p><b>System:</b> For one week the victim vomits up any blood he drinks. He can stomach only ash, roughly half a liter per point, from any source: an ashtray serves as well as a burned corpse. Ash points do nothing but let him rise each night; they cannot fuel Disciplines, raise Attributes, or feed ghouls, though blood already in his body when the curse landed still can.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Uriel\'s Disfavor', desc: `<p>The caster invokes the death-angel whose black wings shrouded Caine, and light itself turns on the victim.</p><p><b>System:</b> For one week all light pains the target, and bright artificial light, headlights, flashlights, floodlights, inflicts one level of aggravated damage per turn of direct exposure. Most victims simply sleep the week away in the dark of their havens.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Valediction', desc: `<p>The path's final word levies Caine's penalty for diablerie, and since most Sabbat climbed to power up somebody's throat, the mere rumor of it teaches humility.</p><p><b>System:</b> Speaking the full verse takes three turns. The target reverts to her original Generation for one week, losing points above the restored maximums; when the curse lifts, the diminished Traits return.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'Thaumaturgical Countermagic', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Less a path than a Discipline in its own right: the art of unmaking blood magic, teachable even to Kindred who could never light a candle with Thaumaturgy proper. The Tremere do not officially export it, and any outsider caught unraveling their workings earns the whole Clan's undivided, frequently fatal, curiosity.</p><p><b>System:</b> Bought and raised like Thaumaturgy (five levels, same experience costs), but it can never be a primary path and grants no rituals. Using it is a free action requiring no dice pool split. To oppose a power or ritual the character needs a Countermagic rating at least equal to its level; the player spends one blood point and rolls dice equal to the rating against the difficulty of the incoming power, each success cancelling one of the opposing caster's. The pool is halved against Necromancy and other mystical Disciplines and useless against non-vampiric magic. Characters barred from Thaumaturgy (such as those with Magic Resistance) may still learn it. A non-Tremere with any rating automatically gains the Flaw Clan Enmity (Tremere) with no freebie compensation, cannot take the power at character creation, and cannot develop it spontaneously; it costs the same as any out-of-Clan Discipline.</p>`, powers: {
      lvl1: { name: '', desc: `<p>Two countermagic dice. Only magic aimed directly at the caster, his clothing, or items he carries can be cancelled.</p>`, primary: '', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: '', desc: `<p>Four countermagic dice.</p>`, primary: '', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: '', desc: `<p>Six countermagic dice. The caster can also shield anyone or anything he is physically touching.</p>`, primary: '', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: '', desc: `<p>Eight countermagic dice.</p>`, primary: '', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: '', desc: `<p>Ten countermagic dice. The caster can cancel magic aimed at, or worked within, a radius of his Willpower in meters around him.</p>`, primary: '', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'Weather Control', type: 'path', img: 'systems/vtm-v20/VTM icons/Thaumaturgy.png',
    system: { level: 0, category: 'thaumaturgical', description: `<p>Weather-witching predates the Tremere by millennia, which explains how often it turns up outside the Clan and outside the Camarilla altogether. The path bends the sky over a few kilometers at most, subtly at low mastery, catastrophically at high, and rarely on an instant's notice.</p><p><b>System:</b> Successes set how fast the sky obeys: one may take a full day, five is nearly immediate. The Storyteller adjusts difficulty by -1 or -2 for nudges the weather was already leaning toward, and +1 or +2 for changes that fight the prevailing conditions. Dropping lightning on a chosen target also requires Perception + Occult (difficulty 6 in the open, 8 under shelter, 10 indoors near a window), and a miss lands the bolt somewhere proportional to the failure. Effects fill the maximum area unless deliberately narrowed, holding the change may demand a Willpower roll (difficulty 6), and indoor use runs +2 difficulty where it is possible at all. Each level lists the strongest phenomenon available.</p>`, powers: {
      lvl1: { name: 'Fog', desc: `<p>Rolling fog: +1 difficulty to Perception rolls of sight and hearing, and ranged attack distances are halved. A light breeze can carry a +1 difficulty to Perception by smell, and the local temperature can be pushed roughly 5 degrees Celsius either way.</p>`, primary: 'willpower', secondary: '', difficulty: 4, cost: '1 blood' },
      lvl2: { name: 'Rain or Snow', desc: `<p>Real precipitation: as Fog, but the Perception penalties climb to +2, and Drive rolls also suffer +2 difficulty.</p>`, primary: 'willpower', secondary: '', difficulty: 5, cost: '1 blood' },
      lvl3: { name: 'High Winds', desc: `<p>Winds near 50 kilometers per hour, gusting to twice that. Firearm attacks take +1 difficulty and thrown weapons or archery +2; in the worst gusts a Dexterity roll (difficulty 6) keeps a character on her feet, and anything unsecured becomes a projectile. Temperature can swing by roughly 10 degrees Celsius.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Storm', desc: `<p>The full performance: the effects of Rain and High Winds at once.</p>`, primary: 'willpower', secondary: '', difficulty: 7, cost: '1 blood' },
      lvl5: { name: 'Lightning Strike', desc: `<p>A called bolt from the sky inflicting 10 dice of lethal damage. Body armor contributes nothing to the soak.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' }
    }}
  },
  {
    name: 'The Sepulchre Path', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>The necromancer's front door to the dead: seeing ghosts, calling them up, and bending them to service, with the deeper powers pinning wraiths in place or striking them directly. Since most Necromancy sooner or later means dealing with ghosts, this is the usual first path. Working any of its powers near something that mattered enormously to the ghost in question, the bathtub they drowned in, the wrecked car that trapped them, a beloved book from a nursery shelf, drops the difficulty by 2.</p>`, powers: {
      lvl1: { name: 'Witness of Death', desc: `<p>Attunes the vampire's senses to perceive ghosts as translucent phantoms. The vampire's eyes flicker with pale blue fire visible only to the dead.</p><p><b>System:</b> Roll Perception + Awareness (diff 5). Success lasts for the scene. A botch means the vampire can see only the dead for the scene (+3 difficulty to vision-based rolls). Ghosts notice the glowing eyes with Perception + Alertness (diff 7).</p>`, primary: 'attributes.perception', secondary: 'abilities.awareness', difficulty: 5, cost: '' },
      lvl2: { name: 'Summon Soul', desc: `<p>Calls a ghost back from the Underworld for conversation. Requires knowing the ghost's name and having an object it contacted in life.</p><p><b>System:</b> Spend 1 blood point. Roll Manipulation + Occult (diff 7 or ghost's Willpower, whichever is higher). A piece of the ghost's corpse reduces difficulty by 1. The ghost cannot leave the vampire's sight. Spend Willpower to dismiss. A botch summons a hostile Spectre instead.</p>`, primary: 'attributes.manipulation', secondary: 'abilities.occult', difficulty: 7, cost: '1 blood' },
      lvl3: { name: 'Compel Soul', desc: `<p>Commands a ghost to perform tasks. Requires the ghost's name and a relevant object.</p><p><b>System:</b> Spend 1 blood point. Resisted roll: Manipulation + Occult vs ghost's Willpower (diff 6 both). Net successes determine control: 1 = one simple safe task, 2 = two tasks or one mildly dangerous one, 3 = one difficult/dangerous task or servitude up to one month, 4 = extreme-risk tasks or slavery for a month (permanent Willpower for a year), 5+ = any task within one month including lethal danger. If the ghost wins, the vampire loses Willpower equal to net successes.</p>`, primary: 'attributes.manipulation', secondary: 'abilities.occult', difficulty: 6, cost: '1 blood' },
      lvl4: { name: 'Haunting', desc: `<p>Binds a ghost to a specific location or object. The wraith risks destruction if it tries to leave.</p><p><b>System:</b> Spend 1 blood point. Roll Manipulation + Occult (diff = ghost's Willpower, min 4; +1 if binding to an object; -1 if using part of the corpse). Each success binds for one night. Spend 1 Willpower for one week, or 1 permanent Willpower for a year and a day. A trapped ghost attempting to leave must make extended Willpower rolls (diff 9, 4 successes) or take aggravated damage.</p>`, primary: 'attributes.manipulation', secondary: 'abilities.occult', difficulty: 4, cost: '1 blood' },
      lvl5: { name: 'Torment', desc: `<p>The vampire strikes a ghost's ectoplasmic form from the physical world, inflicting damage without being struck in return.</p><p><b>System:</b> Roll Stamina + Empathy (diff = ghost's current Willpower). Each success inflicts one level of lethal damage on the ghost. If the ghost loses all health levels, it vanishes into the Underworld and cannot return for one month.</p>`, primary: 'attributes.stamina', secondary: 'abilities.empathy', difficulty: 6, cost: '' }
    }}
  },
  {
    name: 'The Ash Path', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>The art of looking into the lands of the dead, and eventually of reaching in. Among the paths of Necromancy this one costs the most nerve to study, because half of its lessons leave the student exposed to the very wraiths she spies on.</p>`, powers: {
      lvl1: { name: 'Shroudsight', desc: `<p>The caster's eyes pierce the Shroud, the veil between the living world and the Underworld: ghost buildings, dead landscapes, and wraiths themselves come into view. Wraiths tend to notice being stared at, and rarely take it graciously.</p><p><b>System:</b> Perception + Awareness, difficulty 7; the sight lasts one scene.</p>`, primary: 'attributes.perception', secondary: 'abilities.awareness', difficulty: 7, cost: '' },
      lvl2: { name: 'Lifeless Tongues', desc: `<p>Seeing the dead is one thing; this power lets the necromancer converse with them as easily as with the living, at no effort on either side of the veil.</p><p><b>System:</b> Perception + Occult, difficulty 6, plus one point of Willpower.</p>`, primary: 'attributes.perception', secondary: 'abilities.occult', difficulty: 6, cost: '1 willpower' },
      lvl3: { name: 'Dead Hand', desc: `<p>The caster becomes solid to the Underworld: he can strike wraiths, pocket ghostly objects, and climb dead architecture, which to living onlookers is a man scaling empty air. Solidity cuts both ways, and everything over there can hit him back.</p><p><b>System:</b> Spend one Willpower and roll Wits + Occult, difficulty 7, for one scene of contact; each further scene costs a blood point.</p>`, primary: 'attributes.wits', secondary: 'abilities.occult', difficulty: 7, cost: '1 willpower' },
      lvl4: { name: 'Ex Nihilo', desc: `<p>The necromancer walks bodily into the Underworld through a door of his own drawing. There he is a peculiarly solid ghost, and there he can truly die: destruction in the dead lands is final, beyond the reach of any colleague.</p><p><b>System:</b> Draw a doorway in chalk or blood (doors may be prepared ahead), spend two Willpower and two blood, and roll Stamina + Occult, difficulty 8, to force it open. Inside, the vampire keeps his health levels but is harmed only by what deals aggravated damage to ghosts; he may slip through living-world objects at the cost of one health level, staying incorporeal up to Stamina turns. Returning takes another Willpower point and Stamina + Occult at difficulty 6, possibly after a journey back toward the living lands if he has wandered deep; some never find the way. Ghosts cannot be fed upon without other powers, so the only sustenance is the blood he carried in.</p>`, primary: 'attributes.stamina', secondary: 'abilities.occult', difficulty: 8, cost: '2 willpower, 2 blood' },
      lvl5: { name: 'Shroud Mastery', desc: `<p>The master of the path thickens or thins the veil itself, smothering local hauntings or throwing the door wide for his own bound servants.</p><p><b>System:</b> Spend two Willpower, declare raising or lowering, and roll Willpower at difficulty 9. Each success shifts the difficulty of every nearby wraith's attempts to cross or touch the living world by one, up to 10 or down to 3. The Shroud settles back by one point per hour.</p>`, primary: 'willpower', secondary: '', difficulty: 9, cost: '2 willpower' }
    }}
  },
  {
    name: 'The Bone Path', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>The path of the corpse itself: raising bodies, working them, and finding ways to lodge dead souls back into living clay, for an hour or for good.</p>`, powers: {
      lvl1: { name: 'Tremens', desc: `<p>The flesh of a corpse moves once at the caster's whim: an arm flops, dead eyes open, the departed sits up in the coffin at the worst possible moment for the mourners.</p><p><b>System:</b> Spend one blood and roll Dexterity + Occult, difficulty 6. Successes buy complexity, from an instant twitch at one to a full conditional trigger at five (the corpse sits up when the door next opens). No form of this can attack or cause damage.</p>`, primary: 'attributes.dexterity', secondary: 'abilities.occult', difficulty: 6, cost: '1 blood' },
      lvl2: { name: 'Apprentice\'s Brooms', desc: `<p>Corpses rise and work: digging, hauling, sweeping, shambling errands. They neither fight nor defend themselves, and they follow instructions with the literal-mindedness of the truly dead.</p><p><b>System:</b> Roll Wits + Occult, difficulty 7, and spend one blood and one Willpower; successes set how many corpses rise. State the task: they labor until it is finished or until dismemberment, fire, or the like stops them, decaying slowly all the while. Clear, bounded orders work; anything needing judgment fails.</p>`, primary: 'attributes.wits', secondary: 'abilities.occult', difficulty: 7, cost: '1 blood, 1 willpower' },
      lvl3: { name: 'Shambling Hordes', desc: `<p>The classic horror: corpses that rise with orders to kill or to guard, and the patience to wait decades for the chance, long after the flesh has left their bones.</p><p><b>System:</b> Spend a Willpower point and roll Wits + Occult, difficulty 8; each success allows one corpse raised at the cost of one blood point apiece (unpaid successes are wasted). Each zombie holds one simple standing order forever. They fight with Strength 3, Dexterity 2, Stamina 4, Brawl 2, always act last, never dodge, and never heal their 10 health levels; wound penalties do not slow them except from fire or the teeth and claws of supernatural beings. They spend no Willpower but resist as if at 10, have no Mental or Social Traits worth naming, ignore Dominate and Presence entirely, and cannot be pried from their creator's control.</p>`, primary: 'attributes.wits', secondary: 'abilities.occult', difficulty: 8, cost: '1 willpower, 1 blood per corpse' },
      lvl4: { name: 'Soul Stealing', desc: `<p>A power for the living rather than the dead: it shakes a living soul loose from its body, leaving the flesh breathing and empty and the spirit a temporary wraith with one fetter, its own vacant shell.</p><p><b>System:</b> Spend one Willpower and win a contested Willpower roll against the victim, difficulty 6 for both. Each success exiles the soul for one hour while the body lies catatonic. It works on mortals and ghouls, not on Kindred or other supernatural beings until they are truly dead. Popular for preparing hosts for Daemonic Possession.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 willpower' },
      lvl5: { name: 'Daemonic Possession', desc: `<p>The necromancer installs a soul, a consenting ghost or a projected consciousness, into a freshly dead body. The corpse remains a corpse and rots out in a week, but a week embodied is a week many ghosts would trade anything for.</p><p><b>System:</b> The body must be dead less than 30 minutes and the tenant must be willing; nothing can be forced in. Moving a soul into another vampire's not-yet-ashen corpse requires five successes on a contested Willpower roll against the original owner. The tenant uses the body's Physical Abilities and its own Mental ones, never the reverse.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '' }
    }}
  },
  {
    name: 'The Cenotaph Path', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>A path devoted to the joints between the living world and the Shadowlands, built on the observation that a vampire, being a walking corpse, is already such a joint. Its early powers find existing connections; its later ones forge new links outright, usually through brief and unpleasant ritual.</p>`, powers: {
      lvl1: { name: 'A Touch of Death', desc: `<p>The caster reads the residue ghosts leave behind, sensing whether a hand from the far side has touched an object or a person, or merely drifted past.</p><p><b>System:</b> Touch the subject and roll Perception + Awareness, difficulty 6. One success reads ghostly power use in the last turn, two the last three turns, three the last hour along with a ghost's mere touch, four the last day, five the last week including simple passage nearby. A botch reads wrong. Touching a currently possessed subject reveals the rider at once, and the impression counts as an image of that ghost for Sepulchre Path purposes.</p>`, primary: 'attributes.perception', secondary: 'abilities.awareness', difficulty: 6, cost: '' },
      lvl2: { name: 'Reveal the Catene', desc: `<p>Fetters, the objects that chain the dead to the living world, betray themselves to the caster's hands after a few moments of examination.</p><p><b>System:</b> Handle the object (or person) for at least three turns, spend one blood, and roll Perception + Occult, difficulty 7. Success tells whether the subject is a fetter at all; three or more successes name at least one linked ghost, opening it to Sepulchre Path powers. Ghosts already known to the caster are recognized outright. Further ghosts tied to the same object take further uses. A botch closes that object to this power forever.</p>`, primary: 'attributes.perception', secondary: 'abilities.occult', difficulty: 7, cost: '1 blood' },
      lvl3: { name: 'Tread Upon the Grave', desc: `<p>The caster feels for places where the Underworld presses close, the chill spots where ghosts pool, prime hunting ground for the rest of her art.</p><p><b>System:</b> Roll Willpower, difficulty 8, once per scene per area. Success grades the local Shroud as thin, ordinary, or thick; three or more successes also reveal artificial tampering. A botch leaves the caster shuddering and inactive for a turn and costs a temporary Willpower point.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '' },
      lvl4: { name: 'Death Knell', desc: `<p>The caster feels every new ghost being born. When someone dies within about half a mile and fails to move on, the tug of that desperate soul reaches her like a plucked wire.</p><p><b>System:</b> The sense itself is automatic and free. To hunt the new wraith down, spend one Willpower and roll Perception + Occult, difficulty 7: one success gives a vague direction, three add distance to within a few hundred meters, five pinpoint it to arm's reach. A botch sends her confidently the wrong way. Mass deaths, Underworld storms, or rival magic can muddy the signal.</p>`, primary: 'attributes.perception', secondary: 'abilities.occult', difficulty: 7, cost: '1 willpower' },
      lvl5: { name: 'Ephemeral Binding', desc: `<p>The final art forges fetters instead of finding them: the caster's own cursed vitae, smeared on an object or fed to a person, becomes an anchor chaining a chosen ghost to the living world.</p><p><b>System:</b> Coat the object with a full blood point (a living subject must swallow it), spend one Willpower, and roll Manipulation + Occult, difficulty 8. The subject becomes a true fetter to one wraith: known by name or strong impression it can be bound at any distance, otherwise the caster must currently perceive it. The bond works both ways as a natural fetter would, healing the ghost that rests in it, easing the caster's Necromancy against it, easing the ghost's own powers on the subject, and if the fetter is destroyed the wraith is hurled into the deep Underworld, perhaps for good. Duration is one night per success, a week per success for one more Willpower, or a year and a day for a permanent Willpower dot. A botch tells the ghost exactly what was attempted.</p>`, primary: 'attributes.manipulation', secondary: 'abilities.occult', difficulty: 8, cost: '1 blood, 1 willpower' }
    }}
  },
  {
    name: 'The Corpse in the Monster', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>A meditation on the corpse as a doorway between life and death, teaching the necromancer to pull grave-traits over herself or force them on others. The lore descends from the old Discipline called Mortis: the lost Cappadocians favored this path and The Grave's Decay, the Lamia kept the Four Humors, and the Sabbat's Harbingers of Skulls are said to have recovered the first two under the name Mortuus Path, though like most necromancers they still begin with the Sepulchre Path.</p>`, powers: {
      lvl1: { name: 'Masque of Death', desc: `<p>The caster puts on the face of true death, skin drawn tight over bone, or curses another Kindred with the same corpse-look. It makes hiding among the dead of a crypt trivially easy, though sun and fire remain as lethal as ever.</p><p><b>System:</b> Spend one blood. The subject loses two points each of Dexterity and Appearance (minimum 1 and 0) and gains two dice on Intimidation. Held perfectly still, the subject passes for a real corpse unless an examiner scores five successes on Perception + Medicine, difficulty 7; stillness costs a vampire nothing. Inflicting the masque on another requires a touch and a Stamina + Medicine roll against the target's Stamina + 3. It lasts until the next sunset or until its creator releases it.</p>`, primary: 'attributes.stamina', secondary: 'abilities.medicine', difficulty: 6, cost: '1 blood' },
      lvl2: { name: 'Cold of the Grave', desc: `<p>The caster borrows the dead's indifference. Her skin goes cold, her breath mists red-tinged in warm air, and very little seems worth caring about, including pain.</p><p><b>System:</b> Spend one Willpower. For the scene she ignores all wound penalties and gains one die on rolls to resist emotional manipulation, while losing one die from her own attempts to move others. The Beast is not fooled: frenzy rolls proceed as normal.</p>`, primary: '', secondary: '', difficulty: 6, cost: '1 willpower' },
      lvl3: { name: 'Curse of Life', desc: `<p>The caster inflicts a parody of life on another vampire: hunger and thirst, sweat, aching bladder, dulled senses, every mortal indignity with none of mortality's comforts.</p><p><b>System:</b> Spend one Willpower and roll Intelligence + Medicine, difficulty 8, on a target in sight within about 20 meters. Until the next sunset the victim suffers +2 difficulty on all rolls from sheer distraction, may buy the penalty off for one Willpower per scene, and cannot spend blood to raise Physical Attributes at all. He gains no compensating immunity to sun or faith.</p>`, primary: 'attributes.intelligence', secondary: 'abilities.medicine', difficulty: 8, cost: '1 willpower' },
      lvl4: { name: 'Gift of the Corpse', desc: `<p>For a handful of seconds the vampire is neither Damned nor alive, merely a corpse that moves, and a corpse fears none of the things a vampire fears.</p><p><b>System:</b> Spend one Willpower and roll Stamina + Occult, difficulty 8; each success buys one turn. During that time holy artifacts and hallowed ground do nothing, frenzy and Rötschreck cannot touch him, a stake through the heart is just a stabbing, sunlight inflicts at worst bashing damage on bare skin under a clear sky, and fire burns him as it burns a mortal, lethally rather than aggravated. When the last turn ends, whatever he is standing in applies in full and at once: the stake pins him, the flames burn Kindred-hot, and the Red Fear gets its roll.</p>`, primary: 'attributes.stamina', secondary: 'abilities.occult', difficulty: 8, cost: '1 willpower' },
      lvl5: { name: 'Gift of Life', desc: `<p>The path's peak buys a single day of borrowed life: food and drink with taste, pleasure without hunger, a sun that warms instead of executes. The price is an enormous draught of vitae, which usually means somebody dies to pay it.</p><p><b>System:</b> Spend 12 blood points, burned continuously at the fastest rate available (feeding while burning is allowed), then roll Stamina + Occult, difficulty 6, needing one success; a botch is catastrophic, anything from Final Death to an accidental Embrace. Until the following midnight the character is largely proof against the sun (Fortitude soaks it at halved difficulty, and full covering means no damage), enjoys mortal pleasures, stays active through the day without dice pool caps, keeps Fortitude and Auspex (other Disciplines at Storyteller discretion), and handles bashing damage as a vampire; stakes, true faith, and holy artifacts still work, and her blood remains vitae. Frenzy and Rötschreck difficulties are halved (rounded up) for the day, and then the bill comes due: for the next six nights all frenzy difficulties rise by three. Storytellers may also weigh this mockery of life against the character's Path standing.</p>`, primary: 'attributes.stamina', secondary: 'abilities.occult', difficulty: 6, cost: '12 blood' }
    }}
  },
  {
    name: 'The Grave\'s Decay', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>A path drawn from long study of what time does to everything mortal: stone crumbles, flesh rots, and only the necromancer's kind is excused from the process. Its old Cappadocian masters regarded decay as the one universal disease, and learned to prescribe it.</p>`, powers: {
      lvl1: { name: 'Destroy the Husk', desc: `<p>The tidiest solution to an awkward corpse. A few drops of vitae and the body sifts down into a heap of dust, no dogs, no rivers, no risk.</p><p><b>System:</b> Drip one blood point onto a human corpse and roll Intelligence + Medicine, difficulty 6; one success suffices. The body becomes roughly 13 kilograms of anonymous dust over five turns minus the successes rolled.</p>`, primary: 'attributes.intelligence', secondary: 'abilities.medicine', difficulty: 6, cost: '1 blood' },
      lvl2: { name: 'Rigor Mortis', desc: `<p>The caster forces a body, living or undead, into the stiffness of the grave, muscles locking against their owner.</p><p><b>System:</b> Spend one Willpower and roll Intelligence + Medicine, difficulty 7, on a visible target within about 25 meters; each success freezes the target for one turn, treated as if staked. On her own turn the victim may attempt a Willpower roll, difficulty 7, needing two successes to break loose; failing costs a level of bashing damage and the turn. A botch by the caster leaves the target immune to this whole path for 24 hours.</p>`, primary: 'attributes.intelligence', secondary: 'abilities.medicine', difficulty: 7, cost: '1 willpower' },
      lvl3: { name: 'Wither', desc: `<p>A grasped limb shrivels, muscle wasting and bone going brittle in moments. Vampires eventually mend; mortals carry the ruin for life, though it at least stays clean and stable. The power can also age a face, or kill an eye, an ear, or a tongue, but it cannot reach internal organs and grants no quick kills.</p><p><b>System:</b> Spend one Willpower and touch the chosen limb, with a normal Dexterity + Brawl roll against an unwilling target. The limb takes two aggravated wounds, and unless both are soaked it is crippled until both heal, which for mortals is never without supernatural aid. A dead arm has Strength 0, cannot use Potence, and carries almost nothing; a dead leg leaves the target effectively Lame; each ruined eye or ear adds +1 difficulty to relevant Perception rolls, with both gone equating to the Blind or Deaf Flaws; a withered tongue silences as the Mute Flaw; a withered face loses one Appearance per unsoaked wound.</p>`, primary: 'attributes.dexterity', secondary: 'abilities.brawl', difficulty: 6, cost: '1 willpower' },
      lvl4: { name: 'Corrupt the Undead Flesh', desc: `<p>The caster makes dead flesh just alive enough to sicken, saddling a vampire with a plague that mortals catch by simply sharing a room, while other Kindred catch it only from the victim's blood, and then spread it just as well.</p><p><b>System:</b> Spend one Willpower and roll Intelligence + Medicine, difficulty 6, against a target in sight within about 20 meters; the victim resists with Stamina (plus Fortitude) against a difficulty of the caster's Willpower. Infected vampires halve Strength and Wits (round down), lose a point of Dexterity, pay an extra blood point to rise each evening, and must roll Self-Control or Instinct, difficulty 8, when feeding or heave the whole meal back up; infected mortals lose a health level per day instead. Each sunset the victim rolls Stamina against 10 minus the number of sunsets since infection, and on a success the disease breaks, feeding steadies at once, and lost Attribute points return at one per hour. Left alone, it burns out in about a week.</p>`, primary: 'attributes.intelligence', secondary: 'abilities.medicine', difficulty: 6, cost: '1 willpower' },
      lvl5: { name: 'Dissolve the Flesh', desc: `<p>The path turned on the Damned themselves: vitae charged with the grave's hunger crumbles undead flesh to ash exactly as fire or sun would.</p><p><b>System:</b> Spend two blood points and one Willpower to draw off the charged vitae, then douse a single Kindred with it within the next few turns; a sprinkle does nothing, most of it must land. Roll Willpower against the victim's Stamina + 3: each success inflicts one aggravated wound, and each wound turns roughly an eighth of the victim's body to dust, placed at the Storyteller's discretion and regrown only through normal aggravated healing. The resulting ash is reputed to be worth a great deal to certain sorcerers.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '2 blood, 1 willpower' }
    }}
  },
  {
    name: 'Path of the Four Humors', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>An antique medical philosophy weaponized: blood hot and wet, phlegm cold and wet, yellow bile hot and dry, black bile cold and dry, the four fluids whose balance was once thought to govern life. In the undead all four sit in mystic stasis, and this path teaches the necromancer to tap each in turn where other vampires know only vitae. It was the signature art of the Lamia, and since that bloodline's destruction, elder necromancers have ransacked both worlds for surviving teachers.</p>`, powers: {
      lvl1: { name: 'Whispers to the Soul', desc: `<p>A little of the caster's own bile slips out with a whisper and coils into the victim's ear, muttering nightmares day and night from then on.</p><p><b>System:</b> Whisper the target's name into his ear; he resists with Willpower, difficulty 8. Failure means nightmares and waking mutterings for a number of days equal to the caster's Manipulation, costing one die from every dice pool, and the Storyteller may add +1 difficulty to Rötschreck rolls for the duration.</p>`, primary: '', secondary: '', difficulty: 8, cost: '' },
      lvl2: { name: 'Kiss of the Dark Mother', desc: `<p>The caster works black bile into her vitae and coats her lips and fangs with the acrid result, turning her kiss into venom.</p><p><b>System:</b> Spend one blood point as a reflexive action before biting. If the bite lands, its aggravated damage is doubled before soak. Draining works normally and blood loss is unchanged. The venom stays potent until it lands or the caster spends a turn cleaning her mouth.</p>`, primary: '', secondary: '', difficulty: 6, cost: '1 blood' },
      lvl3: { name: 'Dark Humors', desc: `<p>The caster sweats out a chosen humor at its most concentrated, coating her skin or spiking a drink with it, and afterward feels the opposite of what the humor carries.</p><p><b>System:</b> Spend two blood points and choose the humor; skin contact or ingestion delivers it, and the victim resists with Stamina, difficulty 8. Phlegm drains vigor: -2 dice to all pools for the scene. Blood thins the victim's own: every lethal or aggravated wound bleeds for one extra health level on the following turn, and the altered vitae neither ghouls nor bonds anyone who drinks it. Black bile strikes like poison: lethal damage equal to the caster's Stamina, soakable but ignoring armor. Yellow bile drowns the will in visions of death: no Willpower may be spent and Willpower rolls take +2 difficulty for the scene.</p>`, primary: '', secondary: '', difficulty: 6, cost: '2 blood' },
      lvl4: { name: 'Clutching the Shroud', desc: `<p>Blood from a cold corpse is a hot, wet thing transmuted by death, and drinking deep of it edges the necromancer closer to being a true corpse herself: chill, distant, and half in the grave's confidence.</p><p><b>System:</b> Drink and then spend five blood points taken from a corpse dead roughly one to three days; the power begins only once all five are spent. For the rest of the scene the caster gains two extra soak dice against any damage type, an unerring sense of how near everyone present stands to death (sick, dying, ghoul, undead), and free converse with ghosts on a Manipulation + Occult roll, difficulty 5 in a boneyard up to 7 somewhere death rarely visits. The closeness runs both ways: ghostly powers work on her all the more easily.</p>`, primary: 'attributes.manipulation', secondary: 'abilities.occult', difficulty: 6, cost: '5 blood (from corpse)' },
      lvl5: { name: 'Black Breath', desc: `<p>The master of the path drags the black bile up through her dead lungs and breathes out despair itself, a dark mist that makes the living want to die. She feels almost cheerful afterward, having exhaled the worst of herself onto everyone nearby.</p><p><b>System:</b> Spend one Willpower and one blood, and roll Stamina + Athletics, difficulty 7; the cloud spans five meters of diameter per success. Anyone caught inside may escape with Dexterity + Athletics if they have an action; otherwise they roll Willpower (difficulty 8 for mortals, 7 for supernatural beings) and must beat the caster's successes. Mortals who fail set about killing themselves by the most practical means available, for the rest of the scene and at flare-ups after; those who succeed are still death-struck, losing two dice from all pools for the scene. Kindred who fail do not suicide; they drop into torpor as though wounded there, for a duration set by Humanity or Path.</p>`, primary: 'attributes.stamina', secondary: 'abilities.athletics', difficulty: 7, cost: '1 willpower, 1 blood' }
    }}
  },
  {
    name: 'Vitreous Path', type: 'path', img: 'systems/vtm-v20/VTM icons/Necromancy.png',
    system: { level: 0, category: 'necromantic', description: `<p>Entropy itself, harnessed: the rarest of the necromantic arts, invented by the Nagaraja, who call it Nihilistics, and coveted by every death-obsessed lineage since, the Harbingers of Skulls not least. Even necromancers find the material distasteful. Like most of their kind, the Nagaraja learn the Sepulchre Path first and make this their second study.</p>`, powers: {
      lvl1: { name: 'Eyes of the Dead', desc: `<p>The caster sees as the Restless dead see, reading the black entropic markings that death leaves on every soul: how sick, how cursed, how close to the end, and eventually how the end arrives.</p><p><b>System:</b> Roll Perception + Occult, difficulty 6; the deathsight lasts a scene and reads one subject at a time. One success reveals injury, illness, curses, and a rough time of death to within weeks; three add the probable cause, seen as the wounds waiting to happen; five show where and when. The marks of fate rarely move, and the Storyteller may roll secretly so the player cannot tell true readings from noise.</p>`, primary: 'attributes.perception', secondary: 'abilities.occult', difficulty: 6, cost: '' },
      lvl2: { name: 'Aura of Decay', desc: `<p>The caster lets her inner entropy leak, an icy presence a meter across in which machines and dead matter quietly give up: wood warps, metal fatigues, chips crack.</p><p><b>System:</b> No roll; spend blood to condemn a nonliving object within a meter. When next used, the doomed item fails as though its user had botched, the exact mechanism at the Storyteller's whim. One blood point takes a week, two a day, three the end of the scene, four five turns, five a single turn. Because it costs blood, a staked vampire cannot invoke it.</p>`, primary: '', secondary: '', difficulty: 6, cost: '1+ blood' },
      lvl3: { name: 'Soul Feast', desc: `<p>Entropy flows both ways, and the caster has learned to drink it: skimming the ambient charge from a death-soaked place, or seizing a ghost outright and swallowing its substance.</p><p><b>System:</b> Spend one Willpower. From a site of recent or habitual death (a fresh murder scene, a morgue, a cemetery) she draws one to four points of essence, raising the difficulty of all deathly powers there by the same amount for as many nights, and the well stays dry until it refills. Feeding on a ghost instead works like feeding on flesh: the wraith holds up to 10 points, is pinned unless it wins a contested Willpower roll (difficulty 6 both sides), and the half-present caster is open to every ghostly attack while she drinks. The stolen essence works exactly like blood except that it cannot pay for rising at night, and it can be gathered (as power, not food) while walking the dead lands with the Ash Path. A botch seals the Shroud against her feeding for the night and leaves her defenseless between the worlds for several turns.</p>`, primary: 'willpower', secondary: '', difficulty: 6, cost: '1 willpower' },
      lvl4: { name: 'Breath of Thanatos', desc: `<p>The caster inhales, gathers the death within, and exhales a fog of pure entropy, invisible to ordinary eyes, irresistible to Spectres, and poisonous to the living when aimed.</p><p><b>System:</b> Spend one blood and roll Willpower, difficulty 8; one success suffices. Dispersed wide, the mist blankets some 400 meters around the caster, plus 400 more per extra blood point, and draws Spectres for the scene; they ignore the caster unless provoked while savaging anyone else convenient, and other powers may then hook and steer them. Focused instead on a victim, by touch or a Dexterity + Occult roll at difficulty 7, it deals a single aggravated level as sudden sickness and rot, adds +2 difficulty to the victim's social dealings with anyone blind to death's touch, and marks them as tainted to supernatural senses until sunrise; a marked victim cannot be marked again until the fog fades. A botch turns the whole exhalation back on the caster, Spectres included.</p>`, primary: 'willpower', secondary: '', difficulty: 8, cost: '1 blood' },
      lvl5: { name: 'Night Cry', desc: `<p>The breath becomes a scream that echoes on both sides of the Shroud, pouring oblivion through everyone the caster names, to scour them or, strangely, to sweep their doom aside.</p><p><b>System:</b> Choose targets within one meter per dot of Necromancy; spend one Willpower, plus one blood point for each target after the first, within generational limits and never pre-paid. Roll Manipulation + Occult, difficulty 6, declaring blessing or ruin: a blessing grants every target -2 difficulty on all actions for one turn per success, ruin inflicts one aggravated wound per success on each. The cry carries far in both worlds and never goes unnoticed, and a botch may summon Spectres who feel no obligation whatsoever to spare the screamer.</p>`, primary: 'attributes.manipulation', secondary: 'abilities.occult', difficulty: 6, cost: '1 willpower, 1 blood per extra target' }
    }}
  },
];
